apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse
  name: reverse
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverse
  type: LoadBalancer