apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: feed
  name: feed
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      service: feed
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: feed
    spec:
      containers:
      - image: gbolarhan/backend-feed:v1.0.0
        imagePullPolicy: IfNotPresent
        name: feed-api
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
           - configMapRef:
              name: configfile
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30